# Generated by Django 5.2.11 on 2026-02-13 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='sla_hours',
            field=models.IntegerField(default=48),
        ),
        migrations.AddField(
            model_name='department',
            name='transparency_score',
            field=models.FloatField(default=100),
        ),
    ]
