# Generated by Django 6.0.2 on 2026-07-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_department_sla_hours_department_transparency_score'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['transparency_score'], name='departments_transpa_8918d0_idx'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.CheckConstraint(condition=models.Q(('transparency_score__gte', 0.0), ('transparency_score__lte', 100.0)), name='department_transparency_score_range'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.CheckConstraint(condition=models.Q(('sla_hours__gt', 0)), name='department_sla_hours_positive'),
        ),
    ]
