# Generated by Django 6.0.2 on 2026-07-29 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_department_departments_transpa_8918d0_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(help_text='Keyword word or synonym', max_length=100)),
                ('weight', models.IntegerField(default=1, help_text='Weight impact score')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='departments.department')),
            ],
            options={
                'indexes': [models.Index(fields=['word'], name='departments_word_0fb9cb_idx')],
                'unique_together': {('department', 'word')},
            },
        ),
    ]
