# Generated by Django 6.0.2 on 2026-07-29 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('complaint_created', 'Complaint Created'), ('status_updated', 'Status Updated'), ('officer_assigned', 'Officer Assigned'), ('escalated', 'Escalated'), ('user_role_changed', 'User Role Changed'), ('department_updated', 'Department Updated'), ('record_deleted', 'Record Deleted')], max_length=50)),
                ('object_id', models.IntegerField(blank=True, null=True)),
                ('object_type', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action_type', 'created_at'], name='api_auditlo_action__8d2d6f_idx'), models.Index(fields=['object_type', 'object_id'], name='api_auditlo_object__e7bdeb_idx')],
            },
        ),
    ]
