# Generated by Django 5.2.11 on 2026-02-18 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_complaint_address_complaint_city_complaint_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='contact_number',
            field=models.CharField(blank=True, help_text='Contact number for updates', max_length=15, null=True),
        ),
    ]
