# Generated by Django 6.0.2 on 2026-07-29 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0007_complaint_summary_complaintcomment'),
        ('departments', '0003_department_departments_transpa_8918d0_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaintcomment',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='complaint',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='complaintcomment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaintcomment',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_complaints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complaints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complaints', to='departments.department'),
        ),
        migrations.AlterField(
            model_name='complaintcomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['status'], name='complaints__status_7c8de0_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['created_at'], name='complaints__created_805464_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['sla_deadline'], name='complaints__sla_dea_f49b84_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['urgency_level'], name='complaints__urgency_ad2046_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['city'], name='complaints__city_35277b_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['state'], name='complaints__state_79fee1_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['status', 'sla_deadline'], name='complaint_status_sla_idx'),
        ),
        migrations.AddIndex(
            model_name='complaintcomment',
            index=models.Index(fields=['created_at'], name='complaints__created_442785_idx'),
        ),
        migrations.AddConstraint(
            model_name='complaint',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'in_progress', 'resolved', 'escalated', 'administrative_failure'])), name='complaint_status_check'),
        ),
        migrations.AddConstraint(
            model_name='complaint',
            constraint=models.CheckConstraint(condition=models.Q(('urgency_level__in', ['low', 'medium', 'high', 'critical'])), name='complaint_urgency_check'),
        ),
        migrations.AddConstraint(
            model_name='complaint',
            constraint=models.CheckConstraint(condition=models.Q(('latitude__gte', -90.0), ('latitude__lte', 90.0)), name='complaint_latitude_range'),
        ),
        migrations.AddConstraint(
            model_name='complaint',
            constraint=models.CheckConstraint(condition=models.Q(('longitude__gte', -180.0), ('longitude__lte', 180.0)), name='complaint_longitude_range'),
        ),
    ]
