# Generated by Django manual migration

from django.db import migrations, models
import django.db.models.deletion

def migrate_complaint_ownership(apps, schema_editor):
    Complaint = apps.get_model('complaints', 'Complaint')
    
    # Map escalation levels to workflow stages
    # 0 = STAFF, 1 = HOD, 2 = DISTRICT_OFFICER, 3 = STATE_ADMIN
    level_to_stage = {
        0: 'STAFF',
        1: 'HOD',
        2: 'DISTRICT_OFFICER',
        3: 'STATE_ADMIN'
    }
    
    for complaint in Complaint.objects.all():
        complaint.current_owner = complaint.assigned_to
        complaint.workflow_stage = level_to_stage.get(complaint.escalation_level, 'NEW')
        complaint.save(update_fields=['current_owner', 'workflow_stage'])

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),  # Assuming User is in accounts and has 0001
        ('complaints', '0008_alter_complaintcomment_options_complaint_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='current_owner',
            field=models.ForeignKey(blank=True, help_text='The user currently responsible for this complaint with edit rights.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_complaints', to='accounts.user'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='last_escalated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='workflow_stage',
            field=models.CharField(choices=[('NEW', 'New'), ('STAFF', 'Staff'), ('HOD', 'Head of Department'), ('DISTRICT_OFFICER', 'District Officer'), ('STATE_ADMIN', 'State Admin'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='NEW', max_length=20),
        ),
        migrations.RunPython(migrate_complaint_ownership, reverse_code=migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['workflow_stage'], name='complaints__workflo_b453e0_idx'),
        ),
        migrations.AddConstraint(
            model_name='complaint',
            constraint=models.CheckConstraint(condition=models.Q(('workflow_stage__in', ['NEW', 'STAFF', 'HOD', 'DISTRICT_OFFICER', 'STATE_ADMIN', 'RESOLVED', 'CLOSED'])), name='complaint_workflow_stage_check'),
        ),
    ]
