# Generated by Django manual migration

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0009_complaint_workflow_fields'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='complaint',
                    name='sentiment_score',
                    field=models.FloatField(blank=True, help_text='AI-calculated sentiment score (-1.0 to 1.0)', null=True),
                ),
            ],
            database_operations=[
                # Use IF NOT EXISTS to prevent ProgrammingError on databases that already have this column
                # from previously running makemigrations in production
                migrations.RunSQL(
                    sql='ALTER TABLE "complaints_complaint" ADD COLUMN IF NOT EXISTS "sentiment_score" double precision NULL;',
                    reverse_sql='ALTER TABLE "complaints_complaint" DROP COLUMN IF EXISTS "sentiment_score";'
                )
            ]
        )
    ]
