# Generated by Django 6.0.2 on 2026-07-29 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0008_alter_complaintcomment_options_complaint_deleted_at_and_more'),
        ('escalation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='escalationlog',
            options={'ordering': ['-escalated_at']},
        ),
        migrations.AlterField(
            model_name='escalationlog',
            name='escalated_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escalations_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='escalationlog',
            index=models.Index(fields=['escalated_at'], name='escalation__escalat_b08b36_idx'),
        ),
    ]
